[build]
  command = "mkdir -p obj/Release/net8.0/service-worker/ && dotnet publish FunHtmlGames.csproj -c Release -o publish"
  publish = "publish/wwwroot"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
