[build]
  command = "mkdir -p /tmp/funhtmlgames-obj && dotnet publish FunHtmlGames.csproj -c Release -o publish /p:BaseIntermediateOutputPath=/tmp/funhtmlgames-obj/"
  publish = "publish/wwwroot"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
